version: '3.9'
services:
  backend:
    image: jmalloc/echo-server
    ports:
    - "9394:8080"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M
  envoy:
    image: envoyproxy/envoy:v1.22.8
    ports:
      - "8050:8050"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M