version: '3.9'

services:
  backend:
    image: jmalloc/echo-server
    ports:
    - "9394:8080"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M
  haproxy:
    image: haproxytech/haproxy-ubuntu:2.7.3
    container_name: haproxy
    volumes:
    - ./haproxy.cfg:/etc/haproxy/haproxy.cfg
    restart: unless-stopped
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M
