version: '3.9'
services:
  backend:
    image: jmalloc/echo-server
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M
    ports:
    - "9394:8080"
  caddy:
    image: caddy:2.6.4
    ports:
      - "8050:80"
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 512M